name: MacOs

on: [push]

jobs:
  build:
    name: ${{ matrix.cc }}
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        cc: [gcc, clang]
        
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: make
      run: ASAN=1 make
    - name: make test
      run: make test
