name: Windows

on: [push]

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
        
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: make
      run: make
      env:
        CC: gcc
    - name: test
      run: bash scripts/test.sh
